# Name of our workflow
name: Production deploy

# Trigger the workflow on push to main branch
on:
  pull_request:
    branches:
      - main

# List of jobs
# A "job" is a set of steps that are executed on the same runner
jobs:
  # Name of the job
  test-and-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: find cache node module
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm install

      - name: run test
        run: npm run test

      - name: test
        id: test
        run: echo "key=this is a test" >> $GITHUB_OUTPUT
      
      - name: test2
        run: echo "${{ steps.test.outputs.key }}"

      - name: Debug current directory
        run: pwd

      - name: Determine which library be uses
        id: package_manager
        shell: bash
        run: |
          echo "key=$([ -f ./yarn.lock ] && echo "yarn" || ([ -f ./package-lock.json ] && echo "npm") || echo "pnpm")" >> $GITHUB_OUTPUT
        
      - name: Log package_manager
        run: echo ${{ steps.package_manager.outputs.key }}
      

      # - name: build docker
      #   uses: ./.github/actions/build-docker
      #   with:
      #     commit-hash: ${{ github.event.pull_request.head.sha }}
      #     docker-password: ${{ secrets.DockerPassword }}
      #     user-name: tungtk99