# Name of our workflow
name: Production deploy

# Trigger the workflow on push to main branch
on:
  pull_request:
    branches:
      - main

# List of jobs
# A "job" is a set of steps that are executed on the same runner
jobs:
  # Name of the job
  test-and-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: install dependencies
        run: npm install

      - name: run test
        run: npm run test

      - name: build docker
        # run: |
        #   docker build -t cicd-learning-image:${{ github.event.pull_request.head.sha }} .
        #   docker login -u tungtk99 -p ${{ secrets.DockerPassword }}
        #   docker tag cicd-learning-image:${{ github.event.pull_request.head.sha }} tungtk99/cicd-learning-image:${{ github.event.pull_request.head.sha }}
        #   docker push tungtk99/cicd-learning-image:${{ github.event.pull_request.head.sha }}
        uses: build-docker.yml
        with:
          commit-hash: ${{ github.event.pull_request.head.sha }}
          docker-password: ${{ secrets.DockerPassword }}
          user-name: tungtk99